#' 2 weeks of electricity load data from 50 consumers.
#'
#' A dataset containing the electricity consumption time series from 50 consumers of the length of 2 weeks.
#' Every day is 48 measurements (half-hourly data). Each row represents one consumers time series.
#'
#' @format A data frame with 50 rows and 672 variables.
#'
#' @source Anonymized.
"elec_load"

#' Simulated time series dataset.
#'
#' This dataset contains 400 examples of control charts synthetically generated by the process in the paper Time-Series Similarity Queries Employing a Feature-Based Approach.
#' There are six different classes of control charts: 1. Normal 2. Cyclic 3. Increasing trend 4. Decreasing trend 5. Upward shift 6. Downward shift.
#' The first 200 rows of the data.frame (\code{synthetic_control[1:200,]}) are for training and
#' others are for testing (\code{synthetic_control[201:400,]}).
#'
#' @format A data frame with 400 rows and 61 variables.
#' Names of variables are \code{Class} (class number 1-6), \code{V2 - V61} (time series numeric values).
#'
#' @source \url{https://archive.ics.uci.edu/ml/datasets/Synthetic+Control+Chart+Time+Series}
"synthetic_control"
