# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname movave
#' @name movave
#' @title Simple Moving Average
#'
#' @description \code{movave} computes Simple Moving Average (SMA) from a time series.
#'
#' @return Numeric vector of smoothed values
#'
#' @param x Numeric vector
#' @param order - order of simple moving average
#'
#' @examples
#' movave(rnorm(50), 4)
#'
#' @export
movave <- function(x, order) {
    .Call(`_TSrepr_movave`, x, order)
}

#' @rdname fast_stat
#' @name fast_stat
#' @title Fast statistic functions (helpers)
#'
#' @description Fast statistic functions (helpers) for representations computation.
#'
#' @return Numeric value
#'
#' @param x Numeric vector
#'
#' @examples
#' maxC(rnorm(50))
#'
#' @export
maxC <- function(x) {
    .Call(`_TSrepr_maxC`, x)
}

#' @rdname fast_stat
#' @name fast_stat
#' @title Fast statistic functions (helpers)
#'
#' @examples
#' minC(rnorm(50))
#'
#' @export
minC <- function(x) {
    .Call(`_TSrepr_minC`, x)
}

#' @rdname fast_stat
#' @name fast_stat
#' @title Fast statistic functions (helpers)
#'
#' @examples
#' meanC(rnorm(50))
#'
#' @export
meanC <- function(x) {
    .Call(`_TSrepr_meanC`, x)
}

#' @rdname fast_stat
#' @name fast_stat
#' @title Fast statistic functions (helpers)
#'
#' @examples
#' sumC(rnorm(50))
#'
#' @export
sumC <- function(x) {
    .Call(`_TSrepr_sumC`, x)
}

#' @rdname fast_stat
#' @name fast_stat
#' @title Fast statistic functions (helpers)
#'
#' @examples
#' medianC(rnorm(50))
#'
#' @export
medianC <- function(x) {
    .Call(`_TSrepr_medianC`, x)
}

#' @rdname rmse
#' @name rmse
#' @title RMSE
#'
#' @description \code{rmse} Computes RMSE of a forecast.
#'
#' @return numeric value
#'
#' @param x Numeric vector of real values
#' @param y Numeric vector of predicted values
#'
#' @examples
#' rmse(runif(50), runif(50))
#'
#' @export
rmse <- function(x, y) {
    .Call(`_TSrepr_rmse`, x, y)
}

#' @rdname mae
#' @name mae
#' @title MAE
#'
#' @description \code{mae} Computes MAE of a forecast.
#'
#' @return numeric value
#'
#' @param x Numeric vector of real values
#' @param y Numeric vector of predicted values
#'
#' @examples
#' mae(runif(50), runif(50))
#'
#' @export
mae <- function(x, y) {
    .Call(`_TSrepr_mae`, x, y)
}

#' @rdname smape
#' @name smape
#' @title sMAPE
#'
#' @description \code{smape} Computes sMAPE of a forecast.
#'
#' @return numeric value
#'
#' @param x Numeric vector of real values
#' @param y Numeric vector of predicted values
#'
#' @examples
#' smape(runif(50), runif(50))
#'
#' @export
smape <- function(x, y) {
    .Call(`_TSrepr_smape`, x, y)
}

#' @rdname mape
#' @name mape
#' @title MAPE
#'
#' @description \code{mape} Computes MAPE of a forecast.
#'
#' @return numeric value
#'
#' @param x Numeric vector of real values
#' @param y Numeric vector of predicted values
#'
#' @examples
#' mape(runif(50), runif(50))
#'
#' @export
mape <- function(x, y) {
    .Call(`_TSrepr_mape`, x, y)
}

#' @rdname mdae
#' @name mdae
#' @title MDAE
#'
#' @description \code{mdae} Computes MdAE of a forecast.
#'
#' @return numeric value
#'
#' @param x Numeric vector of real values
#' @param y Numeric vector of predicted values
#'
#' @examples
#' mdae(runif(50), runif(50))
#'
#' @export
mdae <- function(x, y) {
    .Call(`_TSrepr_mdae`, x, y)
}

#' @rdname mase
#' @name mase
#' @title MASE
#'
#' @description \code{mase} Computes MASE of a forecast.
#' @return numeric value
#'
#' @param real Numeric vector of real values
#' @param forecast Numeric vector of predicted values
#' @param naive Numeric vector of naive forecast
#'
#' @examples
#' mase(rnorm(50), rnorm(50), rnorm(50))
#'
#' @export
mase <- function(real, forecast, naive) {
    .Call(`_TSrepr_mase`, real, forecast, naive)
}

#' @rdname norm_z
#' @name norm_z
#' @title Z normalization
#'
#' @description \code{norm_z} normalizes data by z-score.
#'
#' @return numeric vector of normalized values
#'
#' @seealso \code{\link[TSrepr]{norm_min_max}}
#'
#' @param x Numeric vector
#'
#' @examples
#' norm_z(runif(50))
#'
#' @export
norm_z <- function(x) {
    .Call(`_TSrepr_norm_z`, x)
}

#' @rdname norm_z_list
#' @name norm_z_list
#' @title Z normalization list
#'
#' @description \code{norm_z_list} normalizes data by z-score and returns normalization parameters.
#'
#' @return list of numeric vector of normalized values and mean-sd values
#'
#' @param x Numeric vector
#'
#' @seealso \code{\link[TSrepr]{norm_min_max_list}}
#'
#' @examples
#' norm_z_list(runif(50))
#'
#' @export
norm_z_list <- function(x) {
    .Call(`_TSrepr_norm_z_list`, x)
}

#' @rdname norm_min_max
#' @name norm_min_max
#' @title min-max normalization
#'
#' @description \code{norm_min_max} normalizes data by min-max method.
#'
#' @return numeric vector of normalized values
#'
#' @param x Numeric vector
#'
#' @seealso \code{\link[TSrepr]{norm_z}}
#'
#' @examples
#' norm_min_max(rnorm(50))
#'
#' @export
norm_min_max <- function(x) {
    .Call(`_TSrepr_norm_min_max`, x)
}

#' @rdname norm_min_max_list
#' @name norm_min_max_list
#' @title min-max normalization list
#'
#' @description \code{norm_min_max_list} normalizes data by min-max method and returns normalization parameters.
#'
#' @return list of numeric vector of normalized values and min-max values
#'
#' @param x Numeric vector
#'
#' @seealso \code{\link[TSrepr]{norm_z_list}}
#'
#' @examples
#' norm_min_max_list(rnorm(50))
#'
#' @export
norm_min_max_list <- function(x) {
    .Call(`_TSrepr_norm_min_max_list`, x)
}

#' @rdname clipping
#' @name clipping
#' @title Creates bit-level (clipping representation) from a vector
#'
#' @description \code{clipping} Computes bit-level (clipping representation) from a vector.
#'
#' @return integer vector of zeros and ones
#'
#' @param x Numeric vector
#'
#' @seealso \code{\link[TSrepr]{trending}}
#'
#' @examples
#' clipping(rnorm(50))
#'
#' @export
clipping <- function(x) {
    .Call(`_TSrepr_clipping`, x)
}

#' @rdname trending
#' @name trending
#' @title Creates trend-level (bit-level) representation from a vector
#'
#' @description \code{trending} Computes trend-level (bit-level) representation from a vector.
#'
#' @return integer vector of zeros and ones
#'
#' @param x Numeric vector
#'
#' @seealso \code{\link[TSrepr]{clipping}}
#'
#' @examples
#' trending(rnorm(50))
#'
#' @export
trending <- function(x) {
    .Call(`_TSrepr_trending`, x)
}

#' @rdname repr_feaclip
#' @name repr_feaclip
#' @title FeaClip representation of time series
#'
#' @description \code{repr_feaclip} computes representation of time series based on feature extraction from bit-level representation.
#'
#' @return numeric vector of length 8
#'
#' @param x Numeric vector
#'
#' @seealso \code{\link[TSrepr]{repr_featrend}, \link[TSrepr]{repr_feacliptrend}}
#'
#' @examples
#' repr_feaclip(rnorm(50))
#'
#' @export
repr_feaclip <- function(x) {
    .Call(`_TSrepr_repr_feaclip`, x)
}

#' @rdname repr_featrend
#' @name repr_featrend
#' @title FeaTrend representation of time series
#'
#' @description \code{repr_featrend} computes representation of time series based on feature extraction from trend-level representation.
#'
#' @return numeric vector of length pieces
#'
#' @param x Numeric vector
#' @param func function of aggregation, can be sumC or maxC or similar aggregation function
#' @param pieces number of parts of time series to split
#' @param order order of simple moving average
#'
#' @seealso \code{\link[TSrepr]{repr_feaclip}, \link[TSrepr]{repr_feacliptrend}}
#'
#' @examples
#' repr_featrend(rnorm(50), maxC)
#'
#' @export
repr_featrend <- function(x, func, pieces = 2L, order = 4L) {
    .Call(`_TSrepr_repr_featrend`, x, func, pieces, order)
}

#' @rdname repr_feacliptrend
#' @name repr_feacliptrend
#' @title TSreprTrend representation of time series
#'
#' @description \code{repr_feacliptrend} computes representation of time series based on feature extraction from bit-level and trend-level representation.
#'
#' @return numeric vector of frequences of features
#'
#' @param x Numeric vector
#' @param func aggregation function for FeaTrend procedure
#' @param pieces number of parts of time series to split
#' @param order order of simple moving average
#'
#' @seealso \code{\link[TSrepr]{repr_featrend}, \link[TSrepr]{repr_feaclip}}
#'
#' @examples
#' repr_feacliptrend(rnorm(50), maxC, 2, 4)
#'
#' @export
repr_feacliptrend <- function(x, func, pieces = 2L, order = 4L) {
    .Call(`_TSrepr_repr_feacliptrend`, x, func, pieces, order)
}

#' @rdname repr_paa
#' @name repr_paa
#' @title PAA - Piecewise Aggregate Approximation
#'
#' @description \code{repr_paa} Computes PAA representation from a vector.
#' @return numeric vector
#'
#' @param x Numeric vector of real values
#' @param q integer of length of the "piece"
#' @param func aggregation function. Can be meanC, medianC, sumC, minC or maxC or similar aggregation function.
#'
#' @seealso \code{\link[TSrepr]{repr_dwt}, \link[TSrepr]{repr_dft}}
#'
#' @examples
#' repr_paa(rnorm(11), 2, meanC)
#'
#' @export
repr_paa <- function(x, q, func) {
    .Call(`_TSrepr_repr_paa`, x, q, func)
}

#' @rdname repr_seas_profile
#' @name repr_seas_profile
#' @title Seasonal profile of time series
#'
#' @description \code{repr_seas_profile} Computes Seasonal Profile representation from a vector.
#'
#' @return numeric vector
#'
#' @param x Numeric vector of real values
#' @param freq integer of length of the season
#' @param func aggregation function. Can be meanC or medianC or similar aggregation function.
#'
#' @seealso \code{\link[TSrepr]{repr_lm}, \link[TSrepr]{repr_gam}, \link[TSrepr]{repr_exp}}
#'
#' @examples
#' repr_seas_profile(rnorm(48*10), 48, meanC)
#'
repr_seas_profile <- function(x, freq, func) {
    .Call(`_TSrepr_repr_seas_profile`, x, freq, func)
}

#' @rdname rleC
#' @name rleC
#' @title RLE (Run Length Encoding) written in C++
#'
#' @description \code{rleC} Computes RLE from bit-level (clipping representation) vector
#'
#' @return list of values and counts of zeros and ones
#'
#' @param x Numeric vector (from \code{clipping})
#'
#' @examples
#' clipped <- clipping(rnorm(50))
#' rleC(clipped)
#'
#' @export
rleC <- function(x) {
    .Call(`_TSrepr_rleC`, x)
}

